Repository Refactorio/RedMew, pull requests merged in 2018-12, with the labels that each got.

#488 Fixed a few left-over requires in Experience
  features/force_control.lua
  map_gen/Diggy/Feature/Experience.lua
Labels: Diggy

#489 Added big rocks to the table
  map_gen/Diggy/Config.lua
  map_gen/Diggy/Feature/AlienSpawner.lua
  map_gen/Diggy/Feature/DiggyCaveCollapse.lua
  map_gen/Diggy/Feature/DiggyHole.lua
  map_gen/Diggy/Feature/Experience.lua
  map_gen/Diggy/Feature/SimpleRoomGenerator.lua
  map_gen/Diggy/Feature/StartingZone.lua
  map_gen/Diggy/Template.lua
Labels: Diggy

#514 Added builders.circular_pattern
  map_gen/shared/builders.lua
Labels: review requested

#587 Update to new config structure
  features/gui/info.lua
Labels: review

#592 Add random_RGB to utils
  utils/core.lua
Labels: review
