Repository Refactorio/RedMew, pull requests merged in 2019-03, with the labels that each got.

#828 Change how rotten_apples checks for military techs
  map_gen/maps/rotten_apples.lua
Labels: Bug-fix

#795 Added improved hydra scaling
  config.lua
  map_gen/shared/hail_hydra.lua
Labels: Feature

#790 Added logic for toggling minable robots
  config.lua
  features/redmew_qol.lua
Labels: Feature

#768 Quadrants
  locale/da/redmew_maps.cfg
  locale/en/redmew_maps.cfg
  map_gen/maps/quadrants.lua
  map_gen/maps/quadrants/compilatron_handler.lua
  map_gen/maps/quadrants/enabled_recipes.lua
  map_gen/maps/quadrants/force_sync.lua
  map_gen/maps/quadrants/item_to_chest.lua
  map_gen/maps/quadrants/restrict_placement.lua
  map_gen/maps/quadrants/scenario.lua
  map_gen/maps/quadrants/switch_team.lua
  map_gen/maps/quadrants/train_crossing.lua
Labels: Map Idea

#866 Fixing danger ores maps
  map_gen/maps/danger_ores.lua
  map_gen/maps/terraforming_danger_ores.lua
Labels: Bug-fix
